# Generated by Django 4.2.7 on 2026-04-30 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Detal nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Detal kodi')),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Bitta detal og'irligi (gram)")),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Bitta detal narxi (so'm)")),
            ],
            options={
                'verbose_name': 'Detal',
                'verbose_name_plural': 'Detallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ishga qabul qilingan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Jami daromad (so'm)")),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Bonus (so'm)")),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Usullar (so'm)")),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name="To'lanadigan maosh (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.worker', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Oylik maosh',
                'verbose_name_plural': 'Oylik maoshlar',
                'ordering': ['-year', '-month', 'worker'],
                'unique_together': {('worker', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ishlangan vazn (kg)')),
                ('pieces_count', models.PositiveIntegerField(editable=False, verbose_name='Detallar soni')),
                ('daily_earnings', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name="Kunlik daromad (so'm)")),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.part', verbose_name='Detal')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.worker', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Kunlik ishlab chiqarish',
                'verbose_name_plural': 'Kunlik ishlab chiqarish',
                'ordering': ['-date', 'worker'],
                'unique_together': {('worker', 'part', 'date')},
            },
        ),
    ]
